import {test,expect} from '@playwright/test';
import crypto from 'node:crypto';
import {buildDashboard} from '../../src/dashboard/model.js';
import {SOURCES} from '../../src/dashboard/sources.js';

test('dashboard renders missing progress, opens detail, prepares chat and fits mobile',async({page})=>{
  const id='11111111-1111-4111-8111-111111111111';
  const payload=Buffer.from(JSON.stringify({sub:id,role:'סופראדמין',exp:Date.now()+3600000})).toString('base64url');
  const sig=crypto.createHmac('sha256','playwright-test-session-secret').update(payload).digest('base64url');
  await page.context().addCookies([{name:'bidoc_session',value:`${payload}.${sig}`,domain:'localhost',path:'/'}]);
  const datasets=Object.fromEntries(Object.entries(SOURCES).map(([k,[table]])=>[k,{table,rows:[],complete:true,status:'ready'}]));
  for(const k of ['files','tasks','documents'])datasets[k]={table:k,rows:[],complete:true,status:'ready'};
  datasets.approval.rows=[{id:'a',title:'אישור תכנון חסר',status:'requested',is_blocking:true}];
  const view={...buildDashboard({project:{id,name:'פרויקט בדיקה'},datasets,schedule:{file:null,files:[],tasks:[]},now:new Date().toISOString(),asOf:'2026-10-04'}),queryToken:'test-token'};
  view.schedule.timeline=[{id:'1',activityKey:'gantt:f:1',title:'עבודות שלד',start:'2026-01-01',end:'2026-03-01'}];
  view.timeline={complete:true,linksComplete:true,events:[{id:'e1',title:'עיכוב ביציקת שלד',date:'2026-02-01',activityKey:'gantt:f:1'},{id:'e2',title:'אירוע לאחר תקופת הלוח',date:'2026-06-01',activityKey:null}]};
  await page.route('**/api/**',r=>r.fulfill({json:{}}));
  await page.route(/^https?:\/\/(?!localhost)/,r=>r.abort());
  await page.route('**/api/dashboard/v1/**',r=>{
    const p=new URL(r.request().url()).pathname;
    const json=p.endsWith('/projects')?{projects:[view.project]}:p.endsWith('/history')?{available:true,snapshots:[]}:p.endsWith('/evidence')?{item:view.attention[0],sources:[]}:p.endsWith('/items')?{items:view.items}:view;
    return r.fulfill({json});
  });
  await page.goto('/#dashboard');
  await expect(page.locator('.db-page h1')).toContainText('פרויקט בדיקה');
  await expect(page.locator('#appSidebar')).toBeHidden();
  await expect(page.locator('.ref-metric')).toHaveCount(6);
  const layout=await page.evaluate(()=>({a:document.querySelector('.ref-attention').getBoundingClientRect().x,c:document.querySelector('.ref-schedule').getBoundingClientRect().x,ai:document.querySelector('.ref-ai').getBoundingClientRect().x}));
  expect(layout.a).toBeLessThan(layout.c);expect(layout.c).toBeLessThan(layout.ai);
  await expect(page.locator('.db-kpi-progress .db-kpi-value')).toHaveText('—');
  await expect(page.locator('.db-kpi-approvals .db-kpi-value')).toHaveText('1');
  await page.getByRole('button',{name:'פרטים ומקורות: אישור תכנון חסר',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('heading',{name:'לו״ז וציר אירועים'})).toBeVisible();
  await expect(page.locator('.db-feed-event')).toHaveCount(1);
  await page.getByRole('button',{name:'כל התקופה',exact:true}).click();
  await expect(page.locator('.db-feed-event')).toHaveCount(2);
  await page.getByRole('button',{name:'פעילות: עבודות שלד',exact:true}).click();
  await expect(page.locator('.db-feed-event')).toHaveCount(1);
  await expect(page.getByRole('region',{name:'פרטי אירוע'})).toContainText('עבודות שלד');
  // The date axis follows the first and last actually visible activity rows.
  view.schedule.timeline=Array.from({length:12},(_,i)=>({id:String(i),activityKey:`gantt:f:${i}`,title:`פעילות ${i+1}`,start:`2026-01-${String(i+1).padStart(2,'0')}`,end:`2026-01-${String(i+2).padStart(2,'0')}`}));
  await page.reload();
  const axis=page.locator('.db-gantt-axis');
  await expect(axis).toHaveAttribute('data-range-start','2026-01-01T00:00:00.000Z');
  await expect(axis).toHaveAttribute('data-range-end','2026-01-06T00:00:00.000Z');
  const scroll=page.getByRole('region',{name:'רשימת פעילויות נגללת'});
  await page.getByRole('button',{name:'כל התקופה',exact:true}).click();
  await scroll.evaluate(node=>{node.scrollTop=40;});
  await expect(axis).toHaveAttribute('data-range-start','2026-01-03T00:00:00.000Z');
  await expect(axis).toHaveAttribute('data-range-end','2026-01-08T00:00:00.000Z');
  await expect(page.getByRole('button',{name:'לפי פעילויות',exact:true})).toHaveAttribute('aria-pressed','true');
  await scroll.evaluate(node=>{node.scrollTop=node.scrollHeight;});
  await expect(axis).toHaveAttribute('data-range-start','2026-01-08T00:00:00.000Z');
  await expect(axis).toHaveAttribute('data-range-end','2026-01-13T00:00:00.000Z');
  await page.setViewportSize({width:390,height:844});
  expect(await page.locator('.db-page').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
  const chatRequests=[];
  let complete;
  await page.route('**/api/chat',async r=>{
    chatRequests.push(r.request().postDataJSON());
    await new Promise(resolve=>{complete=resolve;});
    await r.fulfill({contentType:'text/event-stream',body:'event: result\ndata: '+JSON.stringify({answer:'## מצב הפרויקט\n\nנדרש לבדוק את לוח הזמנים.',messageId:'saved-message-1',sources:[]})+'\n\n'});
  });
  let loadedSession='';
  await page.route('**/api/sessions/*/messages',r=>{
    loadedSession=new URL(r.request().url()).pathname.split('/')[3];
    return r.fulfill({json:{messages:[{id:'saved-message-1',user_message:'סכם את מצב הפרויקט',ai_response:'נדרש לבדוק את לוח הזמנים.'}]}});
  });
  await page.getByRole('button',{name:'שאל את BIDoc',exact:true}).first().click();
  await expect(page.getByRole('dialog')).toContainText('בודק את המקורות');
  await expect(page.locator('#dashboard')).toHaveClass(/active/);
  await expect.poll(()=>chatRequests.length).toBe(1);
  expect(chatRequests[0].message).toBe('סכם את מצב הפרויקט: בדוק את עדכניות לוח הזמנים ואת פערי המידע להערכת מועד המסירה.');
  const popup=page.getByRole('dialog');
  await popup.getByRole('button',{name:'סגור חלון',exact:true}).last().click();
  await page.getByRole('button',{name:'שאל את BIDoc',exact:true}).click();
  expect(chatRequests.length).toBe(1);
  complete();
  await expect(popup).toContainText('נדרש לבדוק את לוח הזמנים.');
  await expect(page.locator('#dashboard')).toHaveClass(/active/);
  await popup.getByRole('button',{name:'סגור חלון',exact:true}).last().click();
  await page.getByRole('button',{name:'שאל את BIDoc',exact:true}).click();
  await expect(popup).toContainText('נדרש לבדוק את לוח הזמנים.');
  expect(chatRequests.length).toBe(1);
  await popup.getByRole('button',{name:'סגור חלון',exact:true}).last().click();
  await page.reload();
  await page.getByRole('button',{name:'שאל את BIDoc',exact:true}).click();
  await expect(popup).toContainText('נדרש לבדוק את לוח הזמנים.');
  expect(chatRequests.length).toBe(1);
  await popup.getByRole('button',{name:'בדוק מחדש',exact:true}).click();
  await expect.poll(()=>chatRequests.length).toBe(2);
  complete();
  await expect(popup).toContainText('נדרש לבדוק את לוח הזמנים.');
  await popup.getByRole('button',{name:'סגור חלון',exact:true}).last().click();
  await page.clock.setFixedTime(new Date(Date.now()+86400000));
  await page.getByRole('button',{name:'שאל את BIDoc',exact:true}).click();
  await expect.poll(()=>chatRequests.length).toBe(3);
  complete();
  await expect(popup).toContainText('נדרש לבדוק את לוח הזמנים.');
  await popup.getByRole('button',{name:'המשך בצ׳אט ←',exact:true}).click();
  await expect(page.locator('#chat')).toHaveClass(/active/);
  expect(loadedSession).toBe(chatRequests[2].sessionId);
  await expect(page.locator('#sessionId')).toHaveValue(chatRequests[2].sessionId);
  await expect(page.locator('#messages')).toContainText('נדרש לבדוק את לוח הזמנים.');
  await page.setViewportSize({width:1280,height:900});
  await expect(page.locator('#appSidebar')).toBeVisible();
  await expect(page.locator('#messageInput')).toHaveValue('');
});
