import DashboardWidget from './DashboardWidget.jsx';
import React,{useState} from 'react';
import DashboardTimeline from './DashboardTimeline.jsx';
const n=v=>v==null?'—':v.toLocaleString('he-IL');
const date=v=>v?new Date(v).toLocaleDateString('he-IL'):'לא דווח';
function Symbol({kind}) {
 const shapes={safety:<><path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6zM12 7v6m0 3v1"/></>,progress:<><rect x="4" y="5" width="16" height="16" rx="2"/><path d="M8 2v6m8-6v6M4 11h16"/></>,critical:<><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v1"/></>,approvals:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/></>,decisions:<><path d="M6 3h9l4 4v14H6zM14 3v5h5M9 12h7m-7 4h5"/></>,schedule:<><path d="M4 18v-5a8 8 0 0 1 16 0v5M2 18h20M12 4v8"/></>,attention:<><circle cx="12" cy="12" r="9"/><path d="M12 7v6m0 3v1"/></>};
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{shapes[kind]||shapes.decisions}</svg>;
}
function PlanningCurve({tasks}){
 const dated=tasks.filter(t=>t.end&&Number.isFinite(Date.parse(t.end))).map(t=>Date.parse(t.end)).sort((a,b)=>a-b);
 if(!dated.length)return <div className="ref-no-chart">אין תאריכים להצגת תכנון</div>;
 const min=dated[0],span=Math.max(86400000,dated.at(-1)-min);
 const points=Array.from({length:9},(_,i)=>({x:32+i*32,y:138-dated.filter(t=>t<=min+span*i/8).length/dated.length*108}));
 const d=points.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ');
 return <div className="ref-curve"><svg viewBox="0 0 320 172" role="img" aria-label="תכנון מצטבר של מועדי סיום הפעילויות, לא ביצוע בפועל">
 {[0,1,2,3,4].map(i=><g key={i}><line x1="32" x2="290" y1={30+i*27} y2={30+i*27} stroke="#e8eef9"/><text x="24" y={33+i*27} textAnchor="end" fontSize="8" fill="#8795b2">{Math.round(dated.length*(4-i)/4)}</text></g>)}
 {points.map((p,i)=><line key={i} x1={p.x} x2={p.x} y1="25" y2="138" stroke="#f0f3fa"/>)}
 <path d={`${d} L288,138 L32,138 Z`} fill="#eaf1ff"/><path d={d} fill="none" stroke="#3775ec" strokeWidth="2.5"/>
 {[0,2,4,6,8].map(i=><text key={i} x={32+i*32} y="155" textAnchor="middle" fontSize="8" fill="#8492b0">{new Date(min+span*i/8).toLocaleDateString('he-IL',{month:'short',year:'2-digit'})}</text>)}
 </svg><span>תכנון מצטבר לפי מועדי סיום · {dated.length} פעילויות עם תאריך</span></div>;
}
export default function DashboardOverview({view,history,onDetail,onAsk,onSchedule,scheduleTarget,pendingJobs=[]}){
 const [question,setQuestion]=useState('');
 const metric=k=>view.metrics.find(m=>m.key===k);
 const attention={key:'attention',label:'נושאים לטיפול',value:view.attentionTotal,note:'נושאים תקפים שסומנו לתשומת לב או בעלי חריג פתוח.'};
 const cards=[{...metric('safety'),key:'safety',label:'אירועי בטיחות',color:'orange',icon:'safety',note:'פתוחים, בטיפול או במעקב'}, {...metric('progress'),label:'התקדמות כוללת',color:'blue',icon:'progress',note:'אין דיווח ביצוע מאומת'}, {...attention,color:'green',icon:'attention',note:'נושאים שסומנו במקור'}, {...metric('critical'),label:'סיכונים קריטיים',color:'red',icon:'critical',note:'פתוחים ודורשים בדיקה'}, {...metric('approvals'),label:'אישורים ממתינים',color:'orange',icon:'approvals',note:'בקשות ואישורים בבדיקה'}, {...metric('decisions'),label:'החלטות לבדיקה',color:'purple',icon:'decisions',note:'כולל החלטות שכבר התקבלו'}, {...metric('schedule'),label:'התראות לו״ז',color:'teal',icon:'schedule',note:'בגרסת הלוח הנבחרת'}];
 const s=view.schedule;
 return <div className="ref-dashboard">
  <section className="ref-metrics" aria-label="מדדי הפרויקט">{cards.map(c=><button key={c.key} className={`ref-metric db-kpi-${c.key} ${c.color}`} onClick={()=>onDetail({type:'metric',metric:c})}><span className="ref-metric-icon"><Symbol kind={c.icon}/></span><span className="ref-metric-content"><b>{c.label}</b><strong className="db-kpi-value">{n(c.value)}{c.unit==='percent'&&c.value!=null?'%':''}</strong><small>{c.note}</small></span><span className="ref-metric-bottom">{c.key==='progress'?'נדרש דיווח כולל לפרויקט':c.value==null?'כיסוי מידע חסר':'הצג פירוט'}<span>↗</span></span></button>)}</section>
  <div className="ref-layout">
   <DashboardWidget title="דורש את תשומת לבך" className="ref-panel ref-attention" id="db-worklist"><header><h2>דורש את תשומת לבך <span>{view.attentionTotal}</span></h2><button onClick={()=>onDetail({type:'metric',metric:attention})}>הצג הכל ←</button></header>
    {view.attention.slice(0,3).map((i,idx)=><article key={i.id} className={`ref-issue issue-${idx}`}><div className="ref-issue-top"><span className={`ref-issue-icon ${pendingJobs.some(j=>j.context.itemId===i.id)?'db-ai-pulse':''}`} aria-label={pendingJobs.some(j=>j.context.itemId===i.id)?'AI מנתח את הנושא':undefined} aria-busy={pendingJobs.some(j=>j.context.itemId===i.id)}><Symbol kind={idx===0?'critical':idx===1?'approvals':'attention'}/></span><div><h3 title={i.title}>{i.title}</h3><p>{i.overdueDays>0?`מועד היעד חלף ב־${n(i.overdueDays)} ימים`:i.reasons?.[0]||'נדרשת בדיקת הנושא'}</p></div><time>{date(i.sourceDate)}</time></div><p className="ref-issue-summary">{i.summary || 'פרטים נוספים ברשומת המקור'}</p><div className="ref-issue-meta">{i.owner||'אחראי לא זוהה'} · {i.closed?'סגור במקור — סומן לבדיקה':'רשומה פתוחה במקור'}</div><div className="ref-issue-actions"><button aria-label={`פרטים ומקורות: ${i.title}`} onClick={()=>onDetail({type:'item',item:i})}>הצג ראיות</button><button onClick={()=>onAsk(i)}>נתח השפעה</button><button onClick={e=>{e.currentTarget.closest('dialog[open]')?.close();onSchedule(i);}}>פתח לו״ז</button></div></article>)}
    {!view.attention.length&&<p className="ref-empty">אין נושאים לטיפול במקורות שנקראו.</p>}
   </DashboardWidget>
   <DashboardWidget title="מצב לוח זמנים" className="ref-panel ref-schedule"><header><h2>מצב לוח זמנים</h2><button onClick={()=>onDetail({type:'schedule'})}>פתח לו״ז ←</button></header><div className="ref-schedule-stats"><div><small>סיום מתוכנן</small><b>{date(s.endDate)}</b></div><div><small>תאריך דיווח בלוח</small><b className="ref-red">{date(s.sourceDate)}</b></div><div><small>התקדמות</small><b>{n(metric('progress').value)}</b></div></div><div className="ref-chart-title"><h3>תכנון מצטבר</h3><span>● תאריכי סיום בלוח</span></div><PlanningCurve tasks={s.timeline}/><p className="ref-data-note">{s.status==='stale'?'נדרש אימות עדכניות הלוח. ':''}הגרף מציג תכנון; אין בסיס להשוואת ביצוע בפועל.</p><div className="ref-schedule-footer"><button onClick={()=>onDetail({type:'schedule'})}><strong>{s.taskCount}</strong><span>פעילויות בלוח</span></button><button onClick={()=>onDetail({type:'metric',metric:metric('schedule')})}><strong className="ref-orange">{n(metric('schedule').value)}</strong><span>התראות פתוחות</span></button><button onClick={()=>onDetail({type:'schedule'})}><strong>{s.milestones.length}</strong><span>אבני דרך מוצגות</span></button></div></DashboardWidget>
   <DashboardWidget title="BIDOC AI" className="ref-panel ref-ai"><div className="ref-ai-header"><span className={pendingJobs.length?'db-ai-pulse':''} aria-busy={pendingJobs.length>0}>✦</span><div><h2>BIDOC AI</h2><small>ניתוח הפרויקט מתוך המקורות</small></div><i>{pendingJobs.length?'מנתח…':'זמין'}</i></div><form onSubmit={e=>{e.preventDefault();if(question.trim())onAsk(null,question);}}><input aria-label="שאלה על הפרויקט" placeholder="שאל על הפרויקט…" value={question} onChange={e=>setQuestion(e.target.value)}/><button disabled={!question.trim()} aria-label="שלח שאלה ל־BIDOC AI">←</button></form><h3>שאלות לדוגמה</h3>{['מה מאחר ומדוע?','מה השתנה בפרויקט?','אילו אישורים מעכבים התקדמות?','מה מסכן את המסירה?'].map((q,i)=><button className="ref-ai-question" key={q} onClick={()=>onAsk(null,q)}><Symbol kind={['progress','attention','approvals','critical'][i]}/>{q}</button>)}<div className="ref-insight"><h3>פער המידע המרכזי</h3><p>אין עדיין דיווח ביצוע כולל מאומת. לוח המקור כולל {s.taskCount} פעילויות; כדאי לבדוק את עדכניות הדיווח לפני הערכת מסירה.</p><button aria-label="שאל את BIDoc" onClick={()=>onAsk(null,'סכם את מצב הפרויקט: בדוק את עדכניות לוח הזמנים ואת פערי המידע להערכת מועד המסירה.')}>הצג ניתוח מלא</button></div><small className="ref-ai-disclaimer">התשובה תיפתח כאן ותישמר גם בהיסטוריית הצ׳אט.</small><details className="ref-history"><summary>תמונות מצב · {history?.snapshots?.length||0}</summary>{history?.snapshots?.slice(0,3).map(s=><button key={s.id} onClick={()=>onDetail({type:'historyItems',snapshot:s,metric:s.metrics.find(m=>m.key==='approvals')})}>{date(s.captured_at)} · אישורים {n(s.metrics.find(m=>m.key==='approvals')?.value)}</button>)}</details></DashboardWidget>
   <DashboardWidget title="לו״ז וציר אירועים" className="ref-gantt"><DashboardTimeline key={`${view.project.id}:${s.fileId}`} view={view} target={scheduleTarget} compact/></DashboardWidget>
   <DashboardWidget title="מקורות אחרונים" className="ref-panel ref-docs"><header><h2>מקורות אחרונים</h2><button onClick={()=>onDetail({type:'health'})}>כיסוי ←</button></header>{view.documents.slice(0,4).map(d=><div className="ref-doc-row" key={d.id}><span><Symbol kind="decisions"/></span><div>{d.url?<a href={d.url} target="_blank" rel="noreferrer">{d.title}</a>:<b>{d.title}</b>}<small>{date(d.ingestedAt)}</small></div></div>)}</DashboardWidget>
   <DashboardWidget title="עדכונים בפרויקט" className="ref-panel ref-updates"><header><h2>עדכונים בפרויקט</h2></header>{view.activity.slice(0,4).map(i=><button className="ref-update-row" key={i.id} onClick={()=>onDetail({type:'item',item:i})}><span><Symbol kind="progress"/></span><div><b>{i.title}</b><small>{date(i.updatedAt)} · עדכון רשומה</small></div></button>)}</DashboardWidget>
  </div>
 </div>;
}
