-- Server-owned audit trail for the per-row Schedule Activity Assignment Agent.
-- Runtime data belongs to the project schedule database. Models and browser
-- clients never receive table privileges; only the backend service role writes.

alter table public.schedule_activity_alert_links
  add column if not exists assignment_method text not null default 'manual',
  add column if not exists assignment_run_id uuid,
  add column if not exists confidence numeric(5,2),
  add column if not exists review_note text;

alter table public.schedule_activity_alert_links
  add constraint schedule_activity_alert_links_assignment_method_ck
    check (assignment_method in ('manual', 'agent_auto', 'agent_approved')),
  add constraint schedule_activity_alert_links_confidence_ck
    check (confidence is null or (confidence >= 0 and confidence <= 100));

create table public.schedule_activity_assignment_runs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null,
  source_table text not null default 'alerts',
  source_id text not null,
  source_event_date date not null,
  schedule_version_id text not null,
  status text not null default 'running',
  decision text,
  selected_activity_key text,
  confidence numeric(5,2),
  runner_up_confidence numeric(5,2),
  threshold_snapshot numeric(5,2) not null,
  margin_snapshot numeric(5,2) not null,
  model_configuration jsonb not null default '{}'::jsonb,
  tool_versions jsonb not null default '{}'::jsonb,
  reason text,
  conflicts jsonb not null default '[]'::jsonb,
  assignment_method text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  requested_by uuid,
  reviewed_by uuid,
  reviewed_at timestamptz,
  review_reason text,
  error_code text,
  workflow_log jsonb,
  run_events jsonb not null default '[]'::jsonb,
  constraint schedule_activity_assignment_runs_project_fk
    foreign key (project_id) references public.projects(id) on delete cascade,
  constraint schedule_activity_assignment_runs_source_ck
    check (source_table = 'alerts' and source_id <> ''),
  constraint schedule_activity_assignment_runs_status_ck
    check (status in ('running', 'review_required', 'no_match', 'auto_assigned', 'approved', 'rejected', 'error')),
  constraint schedule_activity_assignment_runs_decision_ck
    check (decision is null or decision in ('match', 'ambiguous', 'no_match', 'conflict')),
  constraint schedule_activity_assignment_runs_activity_ck
    check (selected_activity_key is null or selected_activity_key like 'gantt:%'),
  constraint schedule_activity_assignment_runs_confidence_ck
    check (
      (confidence is null or (confidence >= 0 and confidence <= 100))
      and (runner_up_confidence is null or (runner_up_confidence >= 0 and runner_up_confidence <= 100))
      and threshold_snapshot >= 0 and threshold_snapshot <= 100
      and margin_snapshot >= 0 and margin_snapshot <= 100
    ),
  constraint schedule_activity_assignment_runs_method_ck
    check (assignment_method is null or assignment_method in ('agent_auto', 'agent_approved'))
);

comment on table public.schedule_activity_assignment_runs is
  'Immutable-input, server-owned audit record for one explicit Schedule assignment-agent action.';
comment on column public.schedule_activity_assignment_runs.model_configuration is
  'Effective model identifiers and prompt hashes; never contains provider secrets or full published prompts.';
comment on column public.schedule_activity_assignment_runs.workflow_log is
  'Masked Workflow inspector payload for this run; contains prompt hashes and telemetry but no provider secrets or full prompts.';

create table public.schedule_activity_assignment_candidates (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.schedule_activity_assignment_runs(id) on delete cascade,
  activity_key text not null,
  rank integer not null,
  final_score numeric(5,2) not null,
  lexical_score numeric(5,2) not null default 0,
  semantic_score numeric(5,2) not null default 0,
  temporal_score numeric(5,2) not null default 0,
  hierarchy_score numeric(5,2) not null default 0,
  historical_score numeric(5,2) not null default 0,
  model_consensus_score numeric(5,2) not null default 0,
  supporting_evidence jsonb not null default '[]'::jsonb,
  contradicting_evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint schedule_activity_assignment_candidates_activity_ck check (activity_key like 'gantt:%'),
  constraint schedule_activity_assignment_candidates_rank_ck check (rank > 0),
  constraint schedule_activity_assignment_candidates_scores_ck check (
    final_score between 0 and 100
    and lexical_score between 0 and 100
    and semantic_score between 0 and 100
    and temporal_score between 0 and 100
    and hierarchy_score between 0 and 100
    and historical_score between 0 and 100
    and model_consensus_score between 0 and 100
  ),
  constraint schedule_activity_assignment_candidates_run_activity_uk unique (run_id, activity_key),
  constraint schedule_activity_assignment_candidates_run_rank_uk unique (run_id, rank)
);

comment on table public.schedule_activity_assignment_candidates is
  'Normalized, versioned signals for the bounded Gantt candidates evaluated in an assignment run.';

alter table public.schedule_activity_alert_links
  add constraint schedule_activity_alert_links_assignment_run_fk
    foreign key (assignment_run_id) references public.schedule_activity_assignment_runs(id) on delete set null;

create index schedule_activity_assignment_runs_project_source_idx
  on public.schedule_activity_assignment_runs (project_id, source_table, source_id, started_at desc);
create index schedule_activity_assignment_runs_project_status_idx
  on public.schedule_activity_assignment_runs (project_id, status, started_at desc);
create index schedule_activity_assignment_candidates_run_score_idx
  on public.schedule_activity_assignment_candidates (run_id, final_score desc);

alter table public.schedule_activity_assignment_runs enable row level security;
alter table public.schedule_activity_assignment_candidates enable row level security;

create or replace function public.bidoc_schedule_commit_activity_assignment_v1(
  p_project_id uuid,
  p_run_id uuid,
  p_activity_key text,
  p_linked_by uuid,
  p_method text,
  p_review_note text default null
) returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_run public.schedule_activity_assignment_runs%rowtype;
  v_candidate public.schedule_activity_assignment_candidates%rowtype;
  v_link_id uuid;
begin
  if p_method not in ('agent_auto', 'agent_approved') then
    raise exception 'unsupported assignment method';
  end if;

  select * into v_run
  from public.schedule_activity_assignment_runs
  where id = p_run_id and project_id = p_project_id
  for update;

  if not found then raise exception 'assignment run not found'; end if;
  if v_run.finished_at is null then raise exception 'assignment run is incomplete'; end if;
  if p_method = 'agent_auto' and v_run.status <> 'review_required' then
    raise exception 'assignment run is not eligible for automatic commit';
  end if;
  if p_method = 'agent_approved' and v_run.status not in ('review_required', 'no_match') then
    raise exception 'assignment run is not awaiting review';
  end if;

  select * into v_candidate
  from public.schedule_activity_assignment_candidates
  where run_id = p_run_id and activity_key = p_activity_key;

  if not found then raise exception 'activity is not a candidate of this run'; end if;
  if exists (
    select 1 from public.schedule_activity_alert_links
    where project_id = p_project_id and source_table = 'alerts' and source_id = v_run.source_id
  ) then
    raise exception 'alert already has an active activity assignment';
  end if;

  insert into public.schedule_activity_alert_links (
    project_id, source_event_id, source_table, source_id, activity_key,
    event_date, linked_by, assignment_method, assignment_run_id, confidence, review_note
  ) values (
    p_project_id, 'alert_' || v_run.source_id, 'alerts', v_run.source_id, p_activity_key,
    v_run.source_event_date, p_linked_by, p_method, p_run_id, v_candidate.final_score,
    nullif(left(coalesce(p_review_note, ''), 1000), '')
  ) returning id into v_link_id;

  update public.schedule_activity_assignment_runs
  set status = case when p_method = 'agent_auto' then 'auto_assigned' else 'approved' end,
      selected_activity_key = p_activity_key,
      confidence = v_candidate.final_score,
      assignment_method = p_method,
      reviewed_by = case when p_method = 'agent_approved' then p_linked_by else reviewed_by end,
      reviewed_at = case when p_method = 'agent_approved' then now() else reviewed_at end
  where id = p_run_id;

  return v_link_id;
end;
$$;

revoke all on table public.schedule_activity_assignment_runs from public, anon, authenticated;
revoke all on table public.schedule_activity_assignment_candidates from public, anon, authenticated;
revoke all on sequence public.schedule_activity_assignment_candidates_id_seq from public, anon, authenticated;
revoke all on function public.bidoc_schedule_commit_activity_assignment_v1(uuid, uuid, text, uuid, text, text) from public, anon, authenticated;

grant select, insert, update, delete on table public.schedule_activity_assignment_runs to service_role;
grant select, insert, update, delete on table public.schedule_activity_assignment_candidates to service_role;
grant usage, select on sequence public.schedule_activity_assignment_candidates_id_seq to service_role;
grant execute on function public.bidoc_schedule_commit_activity_assignment_v1(uuid, uuid, text, uuid, text, text) to service_role;
